import { db } from '../index';
import { productCategories, productAttributes, products, productVariants, productImages, productCollections } from '../schema/catalog';
import { users } from '../schema/users';
import { tenants } from '../schema/tenants';

export async function seedCatalog() {
  console.log('🌱 Seeding catalog data...');

  // Get first tenant and user for seeding
  const [tenant] = await db.select().from(tenants).limit(1);
  const [user] = await db.select().from(users).limit(1);

  if (!tenant || !user) {
    console.log('⚠️  No tenant or user found, skipping catalog seeding');
    return;
  }

  // Seed Product Categories
  const categories = await db.insert(productCategories).values([
    {
      name: 'Electronics',
      description: 'Electronic devices and components',
      code: 'ELECTRONICS',
      level: 1,
      sort_order: 1,
      tenant_id: tenant.id,
      created_by: user.id,
      updated_by: user.id,
    },
    {
      name: 'Office Supplies',
      description: 'Office equipment and supplies',
      code: 'OFFICE_SUPPLIES',
      level: 1,
      sort_order: 2,
      tenant_id: tenant.id,
      created_by: user.id,
      updated_by: user.id,
    },
    {
      name: 'Industrial Equipment',
      description: 'Industrial machinery and equipment',
      code: 'INDUSTRIAL',
      level: 1,
      sort_order: 3,
      tenant_id: tenant.id,
      created_by: user.id,
      updated_by: user.id,
    },
    {
      name: 'Laptops',
      description: 'Portable computers',
      code: 'LAPTOPS',
      level: 2,
      parent_id: (await db.select().from(productCategories).where({ code: 'ELECTRONICS' }))[0]?.id,
      sort_order: 1,
      tenant_id: tenant.id,
      created_by: user.id,
      updated_by: user.id,
    },
    {
      name: 'Desktops',
      description: 'Desktop computers',
      code: 'DESKTOPS',
      level: 2,
      parent_id: (await db.select().from(productCategories).where({ code: 'ELECTRONICS' }))[0]?.id,
      sort_order: 2,
      tenant_id: tenant.id,
      created_by: user.id,
      updated_by: user.id,
    },
  ]).returning();

  // Seed Product Attributes
  const attributes = await db.insert(productAttributes).values([
    {
      name: 'Color',
      code: 'COLOR',
      type: 'select',
      description: 'Product color',
      is_searchable: true,
      is_filterable: true,
      options: ['Black', 'White', 'Silver', 'Blue', 'Red'],
      tenant_id: tenant.id,
      created_by: user.id,
      updated_by: user.id,
    },
    {
      name: 'Size',
      code: 'SIZE',
      type: 'select',
      description: 'Product size',
      is_searchable: true,
      is_filterable: true,
      options: ['Small', 'Medium', 'Large', 'XL'],
      tenant_id: tenant.id,
      created_by: user.id,
      updated_by: user.id,
    },
    {
      name: 'Brand',
      code: 'BRAND',
      type: 'text',
      description: 'Product brand',
      is_searchable: true,
      is_filterable: true,
      tenant_id: tenant.id,
      created_by: user.id,
      updated_by: user.id,
    },
    {
      name: 'Warranty',
      code: 'WARRANTY',
      type: 'select',
      description: 'Warranty period',
      is_searchable: false,
      is_filterable: true,
      options: ['1 Year', '2 Years', '3 Years', '5 Years'],
      tenant_id: tenant.id,
      created_by: user.id,
      updated_by: user.id,
    },
    {
      name: 'Processor',
      code: 'PROCESSOR',
      type: 'text',
      description: 'Processor type',
      is_searchable: true,
      is_filterable: true,
      tenant_id: tenant.id,
      created_by: user.id,
      updated_by: user.id,
    },
    {
      name: 'RAM',
      code: 'RAM',
      type: 'select',
      description: 'RAM capacity',
      is_searchable: true,
      is_filterable: true,
      options: ['4GB', '8GB', '16GB', '32GB', '64GB'],
      tenant_id: tenant.id,
      created_by: user.id,
      updated_by: user.id,
    },
    {
      name: 'Storage',
      code: 'STORAGE',
      type: 'select',
      description: 'Storage capacity',
      is_searchable: true,
      is_filterable: true,
      options: ['128GB', '256GB', '512GB', '1TB', '2TB'],
      tenant_id: tenant.id,
      created_by: user.id,
      updated_by: user.id,
    },
  ]).returning();

  // Seed Products
  const laptopCategory = categories.find(c => c.code === 'LAPTOPS');
  const desktopCategory = categories.find(c => c.code === 'DESKTOPS');

  const seededProducts = await db.insert(products).values([
    {
      sku: 'LAPTOP-001',
      name: 'ThinkPad X1 Carbon',
      description: 'Premium business laptop with Intel Core i7 processor',
      short_description: 'Ultra-lightweight business laptop',
      category_id: laptopCategory?.id,
      brand: 'Lenovo',
      model: 'X1 Carbon',
      manufacturer: 'Lenovo',
      part_number: '20KGS0QK00',
      weight: 1.12,
      weight_unit: 'kg',
      dimensions: { length: 323.5, width: 217.1, height: 14.9, unit: 'mm' },
      color: 'Black',
      material: 'Carbon Fiber',
      country_of_origin: 'China',
      hs_code: '8471.30.00',
      barcode: '8888888888888',
      is_active: true,
      is_featured: true,
      requires_shipping: true,
      track_inventory: true,
      min_order_quantity: 1,
      meta_title: 'ThinkPad X1 Carbon - Premium Business Laptop',
      meta_description: 'Ultra-lightweight business laptop with Intel Core i7 processor',
      url_key: 'thinkpad-x1-carbon',
      tags: ['business', 'premium', 'ultrabook'],
      tenant_id: tenant.id,
      created_by: user.id,
      updated_by: user.id,
    },
    {
      sku: 'LAPTOP-002',
      name: 'MacBook Pro 14"',
      description: 'Apple MacBook Pro with M2 Pro chip',
      short_description: 'Professional laptop with Apple M2 Pro',
      category_id: laptopCategory?.id,
      brand: 'Apple',
      model: 'MacBook Pro',
      manufacturer: 'Apple Inc.',
      part_number: 'MPHE3LL/A',
      weight: 1.6,
      weight_unit: 'kg',
      dimensions: { length: 312.6, width: 221.2, height: 15.5, unit: 'mm' },
      color: 'Space Gray',
      material: 'Aluminum',
      country_of_origin: 'China',
      hs_code: '8471.30.00',
      barcode: '8888888888889',
      is_active: true,
      is_featured: true,
      requires_shipping: true,
      track_inventory: true,
      min_order_quantity: 1,
      meta_title: 'MacBook Pro 14" - Professional Laptop',
      meta_description: 'Apple MacBook Pro with M2 Pro chip',
      url_key: 'macbook-pro-14',
      tags: ['apple', 'professional', 'creative'],
      tenant_id: tenant.id,
      created_by: user.id,
      updated_by: user.id,
    },
    {
      sku: 'DESKTOP-001',
      name: 'Dell OptiPlex 7090',
      description: 'Business desktop computer with Intel Core i5',
      short_description: 'Reliable business desktop',
      category_id: desktopCategory?.id,
      brand: 'Dell',
      model: 'OptiPlex 7090',
      manufacturer: 'Dell Technologies',
      part_number: 'OP7090-MFF',
      weight: 1.2,
      weight_unit: 'kg',
      dimensions: { length: 182, width: 179, height: 35, unit: 'mm' },
      color: 'Black',
      material: 'Plastic',
      country_of_origin: 'USA',
      hs_code: '8471.41.00',
      barcode: '8888888888890',
      is_active: true,
      is_featured: false,
      requires_shipping: true,
      track_inventory: true,
      min_order_quantity: 1,
      meta_title: 'Dell OptiPlex 7090 - Business Desktop',
      meta_description: 'Reliable business desktop computer',
      url_key: 'dell-optiplex-7090',
      tags: ['business', 'desktop', 'dell'],
      tenant_id: tenant.id,
      created_by: user.id,
      updated_by: user.id,
    },
  ]).returning();

  // Seed Product Variants
  const thinkpad = seededProducts.find(p => p.sku === 'LAPTOP-001');
  const macbook = seededProducts.find(p => p.sku === 'LAPTOP-002');

  await db.insert(productVariants).values([
    {
      product_id: thinkpad!.id,
      sku: 'LAPTOP-001-8GB-256GB',
      name: 'ThinkPad X1 Carbon - 8GB RAM, 256GB SSD',
      description: 'ThinkPad X1 Carbon with 8GB RAM and 256GB SSD',
      barcode: '8888888888891',
      weight: 1.12,
      weight_unit: 'kg',
      color: 'Black',
      is_active: true,
      sort_order: 1,
      tenant_id: tenant.id,
      created_by: user.id,
      updated_by: user.id,
    },
    {
      product_id: thinkpad!.id,
      sku: 'LAPTOP-001-16GB-512GB',
      name: 'ThinkPad X1 Carbon - 16GB RAM, 512GB SSD',
      description: 'ThinkPad X1 Carbon with 16GB RAM and 512GB SSD',
      barcode: '8888888888892',
      weight: 1.12,
      weight_unit: 'kg',
      color: 'Black',
      is_active: true,
      sort_order: 2,
      tenant_id: tenant.id,
      created_by: user.id,
      updated_by: user.id,
    },
    {
      product_id: macbook!.id,
      sku: 'LAPTOP-002-16GB-512GB',
      name: 'MacBook Pro 14" - 16GB RAM, 512GB SSD',
      description: 'MacBook Pro 14" with 16GB RAM and 512GB SSD',
      barcode: '8888888888893',
      weight: 1.6,
      weight_unit: 'kg',
      color: 'Space Gray',
      is_active: true,
      sort_order: 1,
      tenant_id: tenant.id,
      created_by: user.id,
      updated_by: user.id,
    },
  ]);

  // Seed Product Collections
  await db.insert(productCollections).values([
    {
      name: 'Featured Products',
      description: 'Our featured product selection',
      code: 'FEATURED',
      is_active: true,
      sort_order: 1,
      tenant_id: tenant.id,
      created_by: user.id,
      updated_by: user.id,
    },
    {
      name: 'Business Laptops',
      description: 'Professional laptops for business use',
      code: 'BUSINESS_LAPTOPS',
      is_active: true,
      sort_order: 2,
      tenant_id: tenant.id,
      created_by: user.id,
      updated_by: user.id,
    },
    {
      name: 'New Arrivals',
      description: 'Latest products in our catalog',
      code: 'NEW_ARRIVALS',
      is_active: true,
      sort_order: 3,
      tenant_id: tenant.id,
      created_by: user.id,
      updated_by: user.id,
    },
  ]);

  console.log('✅ Catalog data seeded successfully');
} 